services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: bk_app
    ports:
      - "8080:80"
    depends_on:
      - server
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: bk_server
    command: npm start
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      APP_ENV: "${APP_ENV:-test}"
      API_HOST: "${API_HOST:-localhost}"
      PORT: "${PORT:-3000}"
      API_TOKEN: "${API_TOKEN}"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local
