{{- if and (not .Values.secrets.existingSecret) .Values.secrets.apiToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nasa-image.apiSecretName" . }}
  labels:
    {{- include "nasa-image.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secrets.secretKey }}: {{ .Values.secrets.apiToken | quote }}
{{- end }}
